import GravityScreening.BulkBoundaryDynamics

/-!
# Exact continuous bulk flow and the quartic interface phase

The normalized Hamiltonian generator is conjugate to `-J`, so its continuous
flow is conjugate to an ordinary rotation.  This file proves the rotation
equations, their group law, the quartic phase selected by the action
amplitudes, and exact equality of the resulting endpoint map with the passive
horizon splitter.  The Cayley midpoint coordinate is therefore a rational
coordinate on an exact flow, not a numerical approximation.
-/

namespace GravityScreening

/-- The exact unit-frequency Hamiltonian rotation generated by `-J`. -/
noncomputable def normalizedRotationFlow
    (phase : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![Real.cos phase, Real.sin phase;
     -Real.sin phase, Real.cos phase]

/-- Position coordinate of the normalized rotation trajectory. -/
noncomputable def normalizedRotationPosition
    (position momentum phase : ℝ) : ℝ :=
  Real.cos phase * position + Real.sin phase * momentum

/-- Momentum coordinate of the normalized rotation trajectory. -/
noncomputable def normalizedRotationMomentum
    (position momentum phase : ℝ) : ℝ :=
  -Real.sin phase * position + Real.cos phase * momentum

/-- Matrix evaluation agrees with the displayed trajectory coordinates. -/
theorem normalizedRotationFlow_mulVec
    (position momentum phase : ℝ) :
    (normalizedRotationFlow phase).mulVec ![position, momentum] =
      ![normalizedRotationPosition position momentum phase,
        normalizedRotationMomentum position momentum phase] := by
  funext i
  fin_cases i <;>
    simp [normalizedRotationFlow, normalizedRotationPosition,
      normalizedRotationMomentum, Matrix.mulVec, dotProduct,
      Fin.sum_univ_succ]

/-- The normalized position trajectory obeys `qdot=p`. -/
theorem normalizedRotationPosition_hasDerivAt
    (position momentum phase : ℝ) :
    HasDerivAt (normalizedRotationPosition position momentum)
      (normalizedRotationMomentum position momentum phase) phase := by
  have h := (Real.hasDerivAt_cos phase).mul_const position |>.add
    ((Real.hasDerivAt_sin phase).mul_const momentum)
  exact h.congr_deriv (by
    simp [normalizedRotationMomentum])

/-- The normalized momentum trajectory obeys `pdot=-q`. -/
theorem normalizedRotationMomentum_hasDerivAt
    (position momentum phase : ℝ) :
    HasDerivAt (normalizedRotationMomentum position momentum)
      (-normalizedRotationPosition position momentum phase) phase := by
  have hsin : HasDerivAt (fun x => -Real.sin x * position)
      (-Real.cos phase * position) phase := by
    have h0 := (Real.hasDerivAt_sin phase).mul_const (-position)
    have hfun : (fun x => -Real.sin x * position) =ᶠ[nhds phase]
        (fun x => Real.sin x * (-position)) := by
      filter_upwards with x
      ring
    exact (h0.congr_of_eventuallyEq hfun).congr_deriv (by ring)
  have h := hsin.add ((Real.hasDerivAt_cos phase).mul_const momentum)
  have hfun : normalizedRotationMomentum position momentum =ᶠ[nhds phase]
      ((fun x => -Real.sin x * position) +
        (fun x => Real.cos x * momentum)) := by
    filter_upwards with x
    simp [normalizedRotationMomentum]
  exact (h.congr_of_eventuallyEq hfun).congr_deriv (by
    unfold normalizedRotationPosition
    ring)

/-- Zero phase is the identity flow. -/
theorem normalizedRotationFlow_zero :
    normalizedRotationFlow 0 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [normalizedRotationFlow]

/-- The exact rotations form a one-parameter group. -/
theorem normalizedRotationFlow_add (phase₁ phase₂ : ℝ) :
    normalizedRotationFlow (phase₁ + phase₂) =
      normalizedRotationFlow phase₁ * normalizedRotationFlow phase₂ := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [normalizedRotationFlow, Matrix.mul_apply, Fin.sum_univ_succ,
      Real.cos_add, Real.sin_add] <;>
    ring

/-- The exact normalized flow is lossless. -/
theorem normalizedRotationFlow_orthogonal (phase : ℝ) :
    (normalizedRotationFlow phase).transpose * normalizedRotationFlow phase = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [normalizedRotationFlow, Matrix.transpose_apply, Matrix.mul_apply,
      Fin.sum_univ_succ] <;>
    nlinarith [Real.sin_sq_add_cos_sq phase]

/-- The exact normalized flow preserves orientation. -/
theorem normalizedRotationFlow_det (phase : ℝ) :
    Matrix.det (normalizedRotationFlow phase) = 1 := by
  simp [normalizedRotationFlow, Matrix.det_fin_two]
  nlinarith [Real.sin_sq_add_cos_sq phase]

/-- Whenever `l` and `d` are the sine and cosine of a phase, the exact
Hamiltonian flow is the passive source splitter. -/
theorem normalizedRotationFlow_eq_passiveSourceSplitter
    (l d phase : ℝ) (hsin : Real.sin phase = l)
    (hcos : Real.cos phase = d) :
    normalizedRotationFlow phase = passiveSourceSplitter l d := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [normalizedRotationFlow, passiveSourceSplitter, hsin, hcos]

/-- The positive quartic interface phase. -/
noncomputable def quarticInterfacePhase (q : ℝ) : ℝ :=
  Real.arcsin (lambda4 q)

/-- The quartic phase has the action overlap as its sine. -/
theorem quarticInterfacePhase_sin (q : ℝ) (hq : 1 < q) :
    Real.sin (quarticInterfacePhase q) = lambda4 q := by
  have hqpos : 0 < q := by linarith
  have hinvpos : 0 < 1 / q := one_div_pos.mpr hqpos
  have hinvlt : 1 / q < 1 := (div_lt_one hqpos).mpr hq
  have hlpos : 0 < lambda4 q := by
    unfold lambda4
    linarith
  have hllt : lambda4 q < 1 := by
    unfold lambda4
    linarith
  exact Real.sin_arcsin (by linarith) (by linarith)

/-- The quartic phase has the retained action amplitude as its cosine. -/
theorem quarticInterfacePhase_cos (q : ℝ) :
    Real.cos (quarticInterfacePhase q) = quarticActionAmplitude q := by
  unfold quarticInterfacePhase quarticActionAmplitude screening
  exact Real.cos_arcsin (lambda4 q)

/-- The selected quartic phase is strictly between zero and a quarter-turn. -/
theorem quarticInterfacePhase_mem_openQuarterTurn
    (q : ℝ) (hq : 1 < q) :
    0 < quarticInterfacePhase q ∧
      quarticInterfacePhase q < Real.pi / 2 := by
  have hqpos : 0 < q := by linarith
  have hinvpos : 0 < 1 / q := one_div_pos.mpr hqpos
  have hinvlt : 1 / q < 1 := (div_lt_one hqpos).mpr hq
  have hlpos : 0 < lambda4 q := by
    unfold lambda4
    linarith
  have hllt : lambda4 q < 1 := by
    unfold lambda4
    linarith
  constructor
  · exact Real.arcsin_pos.mpr hlpos
  · exact Real.arcsin_lt_pi_div_two.mpr hllt

/-- At the quartic phase, the exact continuous normalized Hamiltonian flow is
the parameter-free passive splitter. -/
theorem quartic_exactRotationFlow_eq_passiveSourceSplitter
    (q : ℝ) (hq : 1 < q) :
    normalizedRotationFlow (quarticInterfacePhase q) =
      passiveSourceSplitter (lambda4 q) (quarticActionAmplitude q) := by
  exact normalizedRotationFlow_eq_passiveSourceSplitter
    (lambda4 q) (quarticActionAmplitude q) (quarticInterfacePhase q)
    (quarticInterfacePhase_sin q hq) (quarticInterfacePhase_cos q)

/-- The exact bulk flow in the original canonical coordinates, obtained by
conjugating the ordinary rotation back through the electric source frame. -/
noncomputable def normalizedBulkExactFlow
    (l r phase : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  electricFrameInverse l r * normalizedRotationFlow phase *
    electricFrameTransform l r

/-- The exact bulk flow starts at the identity. -/
theorem normalizedBulkExactFlow_zero
    (l r : ℝ) (hr : r ≠ 0) :
    normalizedBulkExactFlow l r 0 = 1 := by
  rw [normalizedBulkExactFlow, normalizedRotationFlow_zero]
  simp only [Matrix.mul_one]
  exact electricFrameInverse_mul_transform l r hr

/-- The exact bulk flow inherits the one-parameter group law. -/
theorem normalizedBulkExactFlow_add
    (l r phase₁ phase₂ : ℝ) (hr : r ≠ 0) :
    normalizedBulkExactFlow l r (phase₁ + phase₂) =
      normalizedBulkExactFlow l r phase₁ *
        normalizedBulkExactFlow l r phase₂ := by
  simp only [normalizedBulkExactFlow]
  rw [normalizedRotationFlow_add]
  symm
  calc
    (electricFrameInverse l r * normalizedRotationFlow phase₁ *
          electricFrameTransform l r) *
        (electricFrameInverse l r * normalizedRotationFlow phase₂ *
          electricFrameTransform l r) =
      electricFrameInverse l r * normalizedRotationFlow phase₁ *
        (electricFrameTransform l r * electricFrameInverse l r) *
          normalizedRotationFlow phase₂ * electricFrameTransform l r := by
            noncomm_ring
    _ = electricFrameInverse l r * normalizedRotationFlow phase₁ *
          normalizedRotationFlow phase₂ * electricFrameTransform l r := by
            rw [electricFrameTransform_mul_inverse l r hr]
            simp only [Matrix.mul_one]
    _ = electricFrameInverse l r *
          (normalizedRotationFlow phase₁ * normalizedRotationFlow phase₂) *
            electricFrameTransform l r := by noncomm_ring

/-- The electric frame sends the exact original-coordinate flow back to the
ordinary normalized rotation. -/
theorem electricFrame_maps_normalizedBulkExactFlow
    (l r phase : ℝ) (hr : r ≠ 0) :
    electricFrameTransform l r * normalizedBulkExactFlow l r phase *
        electricFrameInverse l r = normalizedRotationFlow phase := by
  rw [normalizedBulkExactFlow]
  simp only [Matrix.mul_assoc]
  rw [electricFrameTransform_mul_inverse l r hr]
  rw [← Matrix.mul_assoc,
    electricFrameTransform_mul_inverse l r hr, Matrix.mul_one]
  exact Matrix.one_mul _

/-- Exact-flow capstone in original bulk coordinates.  Conjugating the bulk
trajectory to the canonical electric frame yields precisely the passive
quartic horizon splitter. -/
theorem quartic_exactBulkFlow_yields_canonicalPassiveSplitter
    (q : ℝ) (hq : 1 < q) (before : Fin 2 → ℝ) :
    let l := lambda4 q
    let d := quarticActionAmplitude q
    let r := quarticSourceFrameAmplitude q
    (quarticElectricSourceFrame q).mulVec
        ((normalizedBulkExactFlow l r (quarticInterfacePhase q)).mulVec before) =
      (passiveSourceSplitter l d).mulVec
        ((quarticElectricSourceFrame q).mulVec before) := by
  dsimp only
  let l := lambda4 q
  let r := quarticSourceFrameAmplitude q
  have hr : r ≠ 0 := by
    exact ne_of_gt (quarticSourceFrameAmplitude_pos q hq)
  rw [quarticElectricSourceFrame, Matrix.mulVec_mulVec]
  have hflow := electricFrame_maps_normalizedBulkExactFlow
    l r (quarticInterfacePhase q) hr
  have hrightInv := electricFrameTransform_mul_inverse l r hr
  have hleft : electricFrameTransform l r * normalizedBulkExactFlow l r
      (quarticInterfacePhase q) = normalizedRotationFlow (quarticInterfacePhase q) *
        electricFrameTransform l r := by
    calc
      electricFrameTransform l r * normalizedBulkExactFlow l r
          (quarticInterfacePhase q) =
          (electricFrameTransform l r * normalizedBulkExactFlow l r
            (quarticInterfacePhase q)) *
              (electricFrameInverse l r * electricFrameTransform l r) := by
            rw [electricFrameInverse_mul_transform l r hr, Matrix.mul_one]
      _ = (electricFrameTransform l r * normalizedBulkExactFlow l r
            (quarticInterfacePhase q) * electricFrameInverse l r) *
              electricFrameTransform l r := by simp only [Matrix.mul_assoc]
      _ = normalizedRotationFlow (quarticInterfacePhase q) *
              electricFrameTransform l r := by rw [hflow]
  rw [hleft, ← Matrix.mulVec_mulVec,
    quartic_exactRotationFlow_eq_passiveSourceSplitter q hq]

/-- The canonical boundary variation is the endpoint relation of the exact
normalized Hamiltonian flow at the quartic phase. -/
theorem quartic_horizonBoundaryStationary_iff_exactRotationFlow
    (q qBefore pBefore qAfter pAfter : ℝ) (hq : 1 < q) :
    IsHorizonBoundaryStationary
        (lambda4 q) (quarticActionAmplitude q)
        qBefore pBefore qAfter pAfter ↔
      ![qAfter, pAfter] =
        (normalizedRotationFlow (quarticInterfacePhase q)).mulVec
          ![qBefore, pBefore] := by
  have hlpos : 0 < lambda4 q := by
    unfold lambda4
    have hqpos : 0 < q := by linarith
    have hinvlt : 1 / q < 1 := (div_lt_one hqpos).mpr hq
    linarith
  rw [horizonBoundaryStationary_iff_passiveSplitter
    (lambda4 q) (quarticActionAmplitude q)
    qBefore pBefore qAfter pAfter (ne_of_gt hlpos)
    (quarticActionAmplitude_sq q hq)]
  rw [quartic_exactRotationFlow_eq_passiveSourceSplitter q hq]

#print axioms GravityScreening.normalizedRotationPosition_hasDerivAt
#print axioms GravityScreening.normalizedRotationMomentum_hasDerivAt
#print axioms GravityScreening.normalizedRotationFlow_add
#print axioms GravityScreening.quartic_exactRotationFlow_eq_passiveSourceSplitter
#print axioms GravityScreening.normalizedBulkExactFlow_zero
#print axioms GravityScreening.normalizedBulkExactFlow_add
#print axioms GravityScreening.electricFrame_maps_normalizedBulkExactFlow
#print axioms GravityScreening.quartic_exactBulkFlow_yields_canonicalPassiveSplitter
#print axioms GravityScreening.quartic_horizonBoundaryStationary_iff_exactRotationFlow

end GravityScreening
