import GravityScreening.ExactBulkFlow

/-!
# The horizon generator as Hamilton's principal function

The quadratic boundary generator is the exact endpoint action of the
unit-frequency oscillator obtained from the source-normalized bulk
Hamiltonian.  Its phase derivative is the conserved oscillator Hamiltonian,
and at the quartic phase it is exactly the previously constructed horizon
boundary functional.
-/

namespace GravityScreening

/-- Unit-frequency oscillator Hamiltonian in the electric source frame. -/
noncomputable def normalizedOscillatorHamiltonian
    (position momentum : ℝ) : ℝ :=
  (position ^ 2 + momentum ^ 2) / 2

/-- Type-one Hamilton principal function with the sign convention used by
`IsHorizonBoundaryStationary`. -/
noncomputable def oscillatorPrincipalFunction
    (phase qBefore qAfter : ℝ) : ℝ :=
  (qBefore * qAfter -
    (Real.cos phase / 2) * (qBefore ^ 2 + qAfter ^ 2)) /
      Real.sin phase

/-- The outgoing canonical momentum generated by the principal function. -/
noncomputable def oscillatorPrincipalOutgoingMomentum
    (phase qBefore qAfter : ℝ) : ℝ :=
  (Real.cos phase * qAfter - qBefore) / Real.sin phase

/-- Substituting the sine and cosine of a phase turns the abstract horizon
generator into the oscillator principal function. -/
theorem horizonBoundaryGeneratingFunction_eq_oscillatorPrincipalFunction
    (l d phase qBefore qAfter : ℝ)
    (hsin : Real.sin phase = l) (hcos : Real.cos phase = d) :
    horizonBoundaryGeneratingFunction l d qBefore qAfter =
      oscillatorPrincipalFunction phase qBefore qAfter := by
  simp [horizonBoundaryGeneratingFunction, oscillatorPrincipalFunction,
    hsin, hcos]

/-- The phase derivative of the principal function is the oscillator energy
evaluated on its outgoing canonical momentum.  This is the Hamilton--Jacobi
equation in the sign convention `F=-S`. -/
theorem oscillatorPrincipalFunction_hasDerivAt_phase
    (phase qBefore qAfter : ℝ) (hsin0 : Real.sin phase ≠ 0) :
    HasDerivAt
      (fun θ => oscillatorPrincipalFunction θ qBefore qAfter)
      (normalizedOscillatorHamiltonian qAfter
        (oscillatorPrincipalOutgoingMomentum phase qBefore qAfter))
      phase := by
  let A : ℝ := qBefore ^ 2 + qAfter ^ 2
  have hnum : HasDerivAt
      (fun θ => qBefore * qAfter - (Real.cos θ / 2) * A)
      ((Real.sin phase / 2) * A) phase := by
    have hcos := (Real.hasDerivAt_cos phase).div_const 2 |>.mul_const A
    have h := (hasDerivAt_const phase (qBefore * qAfter)).sub hcos
    exact h.congr_deriv (by ring)
  have hquot := hnum.div (Real.hasDerivAt_sin phase) hsin0
  have hderiv :
      ((Real.sin phase / 2) * A * Real.sin phase -
          (qBefore * qAfter - (Real.cos phase / 2) * A) *
            Real.cos phase) /
          Real.sin phase ^ 2 =
        normalizedOscillatorHamiltonian qAfter
          (oscillatorPrincipalOutgoingMomentum phase qBefore qAfter) := by
    unfold normalizedOscillatorHamiltonian oscillatorPrincipalOutgoingMomentum
    dsimp only [A]
    field_simp [hsin0]
    nlinarith [Real.sin_sq_add_cos_sq phase]
  have hfinal := hquot.congr_deriv hderiv
  apply hfinal.congr_of_eventuallyEq
  filter_upwards with θ
  simp [oscillatorPrincipalFunction, A]

/-- The electric source frame converts the squeezed bulk quadratic
Hamiltonian exactly into the unit oscillator Hamiltonian. -/
theorem electricFrame_normalizes_bulkQuadraticHamiltonian
    (l d r position momentum : ℝ)
    (hr : r ≠ 0) (hrd : r ^ 2 = d)
    (hd : d ^ 2 = screening l) :
    normalizedOscillatorHamiltonian
        ((electricFrameTransform l r).mulVec ![position, momentum] 0)
        ((electricFrameTransform l r).mulVec ![position, momentum] 1) =
      normalizedBulkQuadraticHamiltonian l d position momentum := by
  subst d
  simp [normalizedOscillatorHamiltonian,
    normalizedBulkQuadraticHamiltonian, electricFrameTransform,
    Matrix.mulVec, dotProduct, Fin.sum_univ_succ]
  unfold screening at hd
  field_simp [hr]
  linear_combination position ^ 2 * hd

/-- At the quartic phase, the exact horizon boundary generator is Hamilton's
principal function of the source-normalized bulk oscillator. -/
theorem quartic_horizonBoundaryGeneratingFunction_eq_principalFunction
    (q qBefore qAfter : ℝ) (hq : 1 < q) :
    horizonBoundaryGeneratingFunction
        (lambda4 q) (quarticActionAmplitude q) qBefore qAfter =
      oscillatorPrincipalFunction
        (quarticInterfacePhase q) qBefore qAfter := by
  exact horizonBoundaryGeneratingFunction_eq_oscillatorPrincipalFunction
    (lambda4 q) (quarticActionAmplitude q) (quarticInterfacePhase q)
    qBefore qAfter (quarticInterfacePhase_sin q hq)
    (quarticInterfacePhase_cos q)

/-- Quartic Hamilton--Jacobi capstone: differentiating the exact boundary
generator with respect to its uniquely fixed phase returns the normalized
outgoing bulk energy. -/
theorem quartic_oscillatorPrincipalFunction_hasDerivAt_phase
    (q qBefore qAfter : ℝ) (hq : 1 < q) :
    HasDerivAt
      (fun θ => oscillatorPrincipalFunction θ qBefore qAfter)
      (normalizedOscillatorHamiltonian qAfter
        (oscillatorPrincipalOutgoingMomentum
          (quarticInterfacePhase q) qBefore qAfter))
      (quarticInterfacePhase q) := by
  have hsinpos : 0 < Real.sin (quarticInterfacePhase q) := by
    rw [quarticInterfacePhase_sin q hq]
    unfold lambda4
    have hqpos : 0 < q := by linarith
    have hinvlt : 1 / q < 1 := (div_lt_one hqpos).mpr hq
    linarith
  exact oscillatorPrincipalFunction_hasDerivAt_phase
    (quarticInterfacePhase q) qBefore qAfter (ne_of_gt hsinpos)

#print axioms GravityScreening.oscillatorPrincipalFunction_hasDerivAt_phase
#print axioms GravityScreening.electricFrame_normalizes_bulkQuadraticHamiltonian
#print axioms GravityScreening.quartic_horizonBoundaryGeneratingFunction_eq_principalFunction
#print axioms GravityScreening.quartic_oscillatorPrincipalFunction_hasDerivAt_phase

end GravityScreening
