import GravityScreening.HorizonInterfaceCayley
import GravityScreening.FirstOrderSourceAction

/-!
# A variational boundary action for the horizon splitter

This file supplies an explicit type-one generating function for the passive
two-channel splitter.  Its two partial derivatives give the canonical
matching conditions.  Those conditions are equivalent both to the passive
splitter and to the centered Cayley/Hamiltonian impulse law.

The construction proves that the proposed matching is generated by a genuine
quadratic boundary action.  It does not prove that the boundary functional is
already forced by the bulk Pauli--Fierz action.
-/

namespace GravityScreening

/-- Symmetric quadratic type-one generating function for the interface.
The variables are the configuration coordinates immediately before and after
the cut. -/
noncomputable def horizonBoundaryGeneratingFunction
    (l d qBefore qAfter : ℝ) : ℝ :=
  (qBefore * qAfter - (d / 2) * (qBefore ^ 2 + qAfter ^ 2)) / l

/-- Exact variation of the boundary generator with respect to the incoming
configuration coordinate. -/
theorem horizonBoundaryGeneratingFunction_hasDerivAt_before
    (l d qBefore qAfter : ℝ) :
    HasDerivAt
      (fun q => horizonBoundaryGeneratingFunction l d q qAfter)
      ((qAfter - d * qBefore) / l) qBefore := by
  unfold horizonBoundaryGeneratingFunction
  have hraw := (hasDerivAt_id qBefore).mul_const qAfter |>.sub
    (((hasDerivAt_id qBefore).pow 2).add
      (hasDerivAt_const qBefore (qAfter ^ 2)) |>.const_mul (d / 2))
      |>.div_const l
  have hraw2 : HasDerivAt _ ((qAfter - d * qBefore) / l) qBefore :=
    hraw.congr_deriv (by norm_num; ring)
  simpa only [id_eq, Pi.sub_apply, Pi.add_apply, Pi.pow_apply] using hraw2

/-- Exact variation of the boundary generator with respect to the outgoing
configuration coordinate. -/
theorem horizonBoundaryGeneratingFunction_hasDerivAt_after
    (l d qBefore qAfter : ℝ) :
    HasDerivAt
      (fun q => horizonBoundaryGeneratingFunction l d qBefore q)
      ((qBefore - d * qAfter) / l) qAfter := by
  unfold horizonBoundaryGeneratingFunction
  have hraw := (hasDerivAt_id qAfter).const_mul qBefore |>.sub
    ((hasDerivAt_const qAfter (qBefore ^ 2)).add
      ((hasDerivAt_id qAfter).pow 2) |>.const_mul (d / 2))
      |>.div_const l
  have hraw2 : HasDerivAt _ ((qBefore - d * qAfter) / l) qAfter :=
    hraw.congr_deriv (by norm_num; ring)
  simpa only [id_eq, Pi.sub_apply, Pi.add_apply, Pi.pow_apply] using hraw2

/-- Canonical type-one boundary stationarity: incoming momentum is the first
partial derivative, and outgoing momentum is minus the second. -/
def IsHorizonBoundaryStationary
    (l d qBefore pBefore qAfter pAfter : ℝ) : Prop :=
  pBefore = (qAfter - d * qBefore) / l ∧
    pAfter = (d * qAfter - qBefore) / l

/-- The boundary variational equations are exactly the passive splitter map. -/
theorem horizonBoundaryStationary_iff_passiveSplitter
    (l d qBefore pBefore qAfter pAfter : ℝ)
    (hl0 : l ≠ 0) (hd : d ^ 2 = screening l) :
    IsHorizonBoundaryStationary l d qBefore pBefore qAfter pAfter ↔
      ![qAfter, pAfter] =
        (passiveSourceSplitter l d).mulVec ![qBefore, pBefore] := by
  unfold IsHorizonBoundaryStationary
  unfold screening at hd
  constructor
  · rintro ⟨hpBefore, hpAfter⟩
    have hqAfter : qAfter = d * qBefore + l * pBefore := by
      apply (eq_div_iff hl0).mp at hpBefore
      nlinarith [hpBefore]
    funext i
    fin_cases i
    · simp [passiveSourceSplitter, Matrix.mulVec, dotProduct,
        Fin.sum_univ_succ, hqAfter]
    · simp [passiveSourceSplitter, Matrix.mulVec, dotProduct,
        Fin.sum_univ_succ]
      calc
        pAfter = (d * qAfter - qBefore) / l := hpAfter
        _ = -l * qBefore + d * pBefore := by
          rw [hqAfter]
          field_simp [hl0]
          linear_combination qBefore * hd
        _ = -(l * qBefore) + d * pBefore := by ring
  · intro hmap
    have hq := congrFun hmap (0 : Fin 2)
    have hp := congrFun hmap (1 : Fin 2)
    simp [passiveSourceSplitter, Matrix.mulVec, dotProduct,
      Fin.sum_univ_succ] at hq hp
    have hp' : pAfter = -l * qBefore + d * pBefore := by
      simpa only [neg_mul] using hp
    constructor
    · apply (eq_div_iff hl0).mpr
      nlinarith [hq]
    · calc
        pAfter = -l * qBefore + d * pBefore := hp'
        _ = (d * qAfter - qBefore) / l := by
          rw [hq]
          field_simp [hl0]
          linear_combination -(qBefore * hd)

/-- The variational boundary equations and the centered Hamiltonian impulse
law select the same data. -/
theorem horizonBoundaryStationary_iff_centeredInterface
    (l d qBefore pBefore qAfter pAfter : ℝ)
    (hl0 : l ≠ 0) (hd : d ^ 2 = screening l) (hdpos : 0 < d) :
    IsHorizonBoundaryStationary l d qBefore pBefore qAfter pAfter ↔
      (interfaceJumpLeft (interfaceCoupling l d)).mulVec
          ![qAfter, pAfter] =
        (interfaceJumpRight (interfaceCoupling l d)).mulVec
          ![qBefore, pBefore] := by
  rw [horizonBoundaryStationary_iff_passiveSplitter
    l d qBefore pBefore qAfter pAfter hl0 hd]
  constructor
  · intro hmap
    rw [hmap]
    have hmatrix := passiveSourceSplitter_satisfies_centeredInterface
      l d hd hdpos
    rw [Matrix.mulVec_mulVec, hmatrix]
  · intro hjump
    have hleftInv := interfaceJumpLeftInverse_mul_left
      (interfaceCoupling l d)
    calc
      ![qAfter, pAfter] = (1 : Matrix (Fin 2) (Fin 2) ℝ).mulVec
          ![qAfter, pAfter] := by simp
      _ = (interfaceJumpLeftInverse (interfaceCoupling l d) *
            interfaceJumpLeft (interfaceCoupling l d)).mulVec
          ![qAfter, pAfter] := by rw [hleftInv]
      _ = (interfaceJumpLeftInverse (interfaceCoupling l d)).mulVec
            ((interfaceJumpLeft (interfaceCoupling l d)).mulVec
              ![qAfter, pAfter]) :=
        (Matrix.mulVec_mulVec ![qAfter, pAfter]
          (interfaceJumpLeftInverse (interfaceCoupling l d))
          (interfaceJumpLeft (interfaceCoupling l d))).symm
      _ = (interfaceJumpLeftInverse (interfaceCoupling l d)).mulVec
            ((interfaceJumpRight (interfaceCoupling l d)).mulVec
              ![qBefore, pBefore]) := by rw [hjump]
      _ = (interfaceJumpLeftInverse (interfaceCoupling l d) *
            interfaceJumpRight (interfaceCoupling l d)).mulVec
          ![qBefore, pBefore] := Matrix.mulVec_mulVec _ _ _
      _ = (interfaceCayleyMap (interfaceCoupling l d)).mulVec
          ![qBefore, pBefore] := by
            rw [interfaceJumpLeftInverse_mul_right]
      _ = (passiveSourceSplitter l d).mulVec ![qBefore, pBefore] := by
        rw [interfaceCayleyMap_eq_passiveSourceSplitter l d hd hdpos]

/-- Quartic specialization: the boundary variation and centered Hamiltonian
impulse coincide with no additional continuous coefficient. -/
theorem quartic_horizonBoundaryStationary_iff_centeredInterface
    (q qBefore pBefore qAfter pAfter : ℝ) (hq : 1 < q) :
    let d := Real.sqrt ((2 * q - 1) / q ^ 2)
    IsHorizonBoundaryStationary (lambda4 q) d
        qBefore pBefore qAfter pAfter ↔
      (interfaceJumpLeft (interfaceCoupling (lambda4 q) d)).mulVec
          ![qAfter, pAfter] =
        (interfaceJumpRight (interfaceCoupling (lambda4 q) d)).mulVec
          ![qBefore, pBefore] := by
  dsimp only
  let d : ℝ := Real.sqrt ((2 * q - 1) / q ^ 2)
  have hq0 : q ≠ 0 := by linarith
  have hspos : 0 < (2 * q - 1) / q ^ 2 :=
    div_pos (by linarith) (sq_pos_of_ne_zero hq0)
  have hdpos : 0 < d := by
    dsimp [d]
    exact Real.sqrt_pos.2 hspos
  have hd : d ^ 2 = screening (lambda4 q) := by
    dsimp [d]
    rw [quartic_screening_identity q hq0]
    exact Real.sq_sqrt hspos.le
  have hlpos : 0 < lambda4 q := by
    unfold lambda4
    have hinvlt : 1 / q < 1 := (div_lt_one (by linarith)).mpr hq
    linarith
  exact horizonBoundaryStationary_iff_centeredInterface
    (lambda4 q) d qBefore pBefore qAfter pAfter
    (ne_of_gt hlpos) hd hdpos

#print axioms GravityScreening.horizonBoundaryGeneratingFunction_hasDerivAt_before
#print axioms GravityScreening.horizonBoundaryGeneratingFunction_hasDerivAt_after
#print axioms GravityScreening.horizonBoundaryStationary_iff_passiveSplitter
#print axioms GravityScreening.horizonBoundaryStationary_iff_centeredInterface
#print axioms GravityScreening.quartic_horizonBoundaryStationary_iff_centeredInterface

end GravityScreening
